# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3cd3cfad3a9a7707c3c1cc9bf954e85d17b914c0de97087216d3ce5aa0025b1d4c6661c8d193275ce920185ad90e414417b0c5e9ef3b0bfb1e8ea8608d68437

test:
  secret_key_base: 9f0b02b7ba486e21c85fdf10312b4bf1a8f8d63693bff3ea432352b8fb0c992a73896f0d9d3a265a45d1ecd89baa66b187ad8c8aa43da7412474b2bbd15f5e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
